spring.application.name=spring-boot-secure-API
server.port=8081

server.tomcat.max-swallow-size = 1024MB
server.tomcat.max-http-form-post-size = 1024MB

# Configuration du contexte du servlet
server.servlet.context-path = /artim
server.error.include-message = always
server.error.include-binding-errors = always

# Configuration des fichiers multipart
spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size = 1024MB
spring.servlet.multipart.max-request-size = 1024MB

# Base de donnees
spring.datasource.url = jdbc:postgresql://localhost:5432/ARTIM
spring.datasource.username = postgres
spring.datasource.password = root
spring.datasource.hikari.connectionTimeout = 20000
spring.datasource.hikari.maximumPollSize = 5
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

#spring.security.user.name = root
#spring.security.user.password = 1234

#logging.level.root=DEBUG
#logging.level.com.cosama.artim.services=DEBUG

file.path.excel=src/main/resources/excel/place.xlsx
file2.path.excel=src/main/resources/excel/nationality.xlsx
file3.path.excel=src/main/resources/excel/typeBagage.xlsx
file4.path.excel=src/main/resources/excel/tarif_bagages.xlsx
file5.path.excel=src/main/resources/excel/groupe_criteres.xlsx
file6.path.excel=src/main/resources/excel/tarif_places.xlsx
file7.path.excel=src/main/resources/excel/passagers.xlsx
file8.path.excel=src/main/resources/excel/clt_en_compte.xlsx
file9.path.excel=src/main/resources/excel/profils.xlsx

server.max-http-header-size=64kb